licenses(["notice"])

cc_library(
    name = "common",
    hdrs = [
        "utils.h",
        "gavril.h",
        "union.h",
    ],
    deps = [
        "//benchmarks/KCore/JulienneDBS17:KCore",
        "//gbbs",
    ],
)

package(
    default_visibility = ["//visibility:public"],
)
